#pragma once
#include "Constants.h"

namespace LanguagePack
{
	std::vector<std::vector<std::string>> vector_of_strings = {
		{ "max_speed","max_accelerating","max_braking","hand_brake_value","durability","visibility","turn_mod","drift_mod" },
		{ "asphalt","grass","gravel","sand","mud","ice" },
		{ "New Game ", "Multiplayer ", "Game Information",  "Ranking ", "Options ", "Credits ", "Exit" },
		{ "Introduction"},
		{ "","Tour of Turns is turn-based racing game where player with the lowest final score wins.",
			"","Before the start of the game, player selects tour on which he will race. Additionally he chooses a car and a tires that greatly impact chances of winning the race.",
			"","The actual race is divided into segments - parts of the tour on which player takes actions.",
			"","Each action consists of two different elements : speed changing phase and attack phase.",
			"","After completing the action, the player moves to the next segment and the new turn begins.",
			"","When player finishes the race his score is added to ranking file."},
		{ "Name", "Number of AIs", "Tours", "Cars", "Tires", "Next" },
		{ "Host game", "Search game", "Back" },
		{ "Main Color", "Secondary Color", "Music volume", "Hamachi connection", "Back" },
		{ "Player Informations", "Tour Informations", "tour_length", "turns", "current_champion", "winrate", "average_place"},
		{ "green","cyan","red","magenta","brown","light gray","dark gray","blue","light green", "light cyan","light red","light magenta","yellow","white" },
		{ "Speed up","Slow down","Hand-Brake","Do nothing","Abaddon Race" },
		{ "Chance: ", "Estimated time: ", "Durability burning: ", "Estimated speed: " },
		{ "PLACE", "RACER", "SCORE" },
		{ "You can speed up by (0 to " , "You can slow down by (0 to " , "Hand brake value is - ", "You can just wait if you're moving..." ,"Remember only weak ones surrenders" },
		{ " You're racing as: ",  " Your current speed is: ", " Your vehice has ", " durability   " },
		{ "In front of you: ", "Close to you: ", "At some distance: ", "A little further: ", "At a considerable distance: ", "Far ahead: ", "Barely noticeable: " },
		{ "Infobox  " , "Attack box" , "Chance of succeeding" },
		{ "Turn on asphalt - safe speed is around ", "Straight road, terrain is asphalt", "Turn on grass - safe speed is around ", "Straight grassy road" , "Turn on gravel - safe speed is around " , "Straight road, gravel",
			"Turn on sand - safe speed is around ", "Linear part of tour, but sandy",  "Turn on mud - safe speed is around ", "Muddy road, without turn" , "Turn on ice - safe speed is around ", "Slippery road with ice" },
		{ "Paul Harackovy", "Mark Driver", "Max McDonald", "Gordon Goodman", "Miguela Aguela", "Hans Ufner", "Isao Fujimoto", "Igor Belov", "John Hill", "Andrew Anderson", "Jane Turning", "Lester King", "Drew McNeil",
			"Sam Samson", "Gaston Reveneu", "Roman Torbon", "Helga Dick", "Mogore the Ogre", "David Black", "Reta Rdest", "Bloodwyn", "Quality Racer", "Sui Cide", "Ivan Atakovic", "Blu Apostrof" },
		{ " have manage to turn, ", " had mistaken, ", " badly crashed !!! ", " crashed !!!, " ," had an dangerous accident, " ," got off the route, " ," fell into a dangerous slip, " ," slipped, " },
		{ "","Hello I am Michal Balicki and I am really happy that you are playing my game.",
			"","Tour of Turns was my first real project in my programming way and I hope you like it.",
			"","I would like to thank people who helped me with this project.",
			"Krystian Grzegorzewicz ", "without him the game wouldn't be created.",
			"","He was patiently listening what problems do I have with ToT and the most important he gave me a main idea of the game.",
			"Marek Loek ", "for making an icon image and inspiring me to hard work.",
			"Marcin Marzec ", "for giving me inspiration.",
			"","I admire how much work he put into Pan Zniszczenia and Zniwiarz Dusz maps for HoMM3, based on Diablo universe.",
			"Miroslaw Zelent ", "for getting me interested in programming"},
		{ "on", "off" },
		{ "  _______  ___         ___     ", "     |    |   | |   | |   |    ", "     |    |   | |   | |___|    ", "     |    |   | |   | |  \\     ", "     |    |___| |___| |   \\    ", "                               ",
			"                               ", "                               ", "                               ", "                               ", "_______        ___    __   __  ", "   |    |   | |   |  |  | |    ",
			"   |    |   | |___|  |  | |__  ", "   |    |   | |  \\   |  |    | ", "   |    |___| |   \\  |  | ___| "},
		{ " ___   ___", "|   | |   ", "|   | |_  ", "|   | |   ", "|___| |   "},
		{ "You can't start new race with current game state, please repair files or reinstall game", "Files not found, please reinstall your game or repair missing files" , "There are no ranking files" , " cannot be read, please repair or delete corrupted files" },
		{ "Unplayable Game",  "Missing Files", "Corupted Files" },
		{ "Racer", " - Do you really want to do this ? (Y/N) ", "RIP, ", " dezintegrated his vehichle...","Don't attack" ," - You can't do this because you aren't moving...",
			"META" , " lost " , "required - ", " highest roll - ", " lowest roll - ", "in result of other racers behaviour", " speed,", "________________________________________________________  " }
	};
}